/**
 * MetaDataTest.java
 *
 * This file was generated by XMLSpy 2014 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.MetaDataTest;

import com.altova.*;
import com.altova.types.*;
import com.MetaData.*;

public class MetaDataTest {
	protected static void example() throws Exception {
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   com.MetaData.MetaData doc = com.MetaData.MetaData.createDocument();			
			//   com.MetaData.VoIBaseAttrType root = doc.VoIBaseAttr.append();
			//   ...
			//   doc.saveToFile("MetaData1.xml", true);
			//
			// Example code to load and save a structure:
			//   com.MetaData.MetaData doc = com.MetaData.MetaData.loadFromFile("MetaData1.xml");
			//   com.MetaData.VoIBaseAttrType root = doc.VoIBaseAttr.first();
			//   ...
			//   doc.saveToFile("MetaData1.xml", true);


	}

	public static void main(String args[]) {
		try {
			System.out.println("MetaData Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
