////////////////////////////////////////////////////////////////////////
//
// ContextType.java
//
// This file was generated by XMLSpy 2014 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

package com.MetaData;

public class ContextType extends com.altova.xml.TypeBase
{
	public static com.altova.xml.meta.ComplexType getStaticInfo() { return new com.altova.xml.meta.ComplexType(com.MetaData.MetaData_TypeInfo.binder.getTypes()[com.MetaData.MetaData_TypeInfo._altova_ti_altova_ContextType]); }
	
	public ContextType(org.w3c.dom.Node init)
	{
		super(init);
		instantiateMembers();
	}

	private void instantiateMembers()
	{

		AppDomainCntx= new MemberElement_AppDomainCntx (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_ContextType._AppDomainCntx]);
		QoISpatialCntxAttr= new MemberElement_QoISpatialCntxAttr (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_ContextType._QoISpatialCntxAttr]);
		QoITemperalCntxAttr= new MemberElement_QoITemperalCntxAttr (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_ContextType._QoITemperalCntxAttr]);
	}
	// Attributes


	// Elements
	
	public MemberElement_AppDomainCntx AppDomainCntx;

		public static class MemberElement_AppDomainCntx
		{
			public static class MemberElement_AppDomainCntx_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_AppDomainCntx member;
				public MemberElement_AppDomainCntx_Iterator(MemberElement_AppDomainCntx member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					AppDomainCntxType2 nx = new AppDomainCntxType2(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_AppDomainCntx (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public AppDomainCntxType2 at(int index) {return new AppDomainCntxType2(owner.getElementAt(info, index));}
			public AppDomainCntxType2 first() {return new AppDomainCntxType2(owner.getElementFirst(info));}
			public AppDomainCntxType2 last(){return new AppDomainCntxType2(owner.getElementLast(info));}
			public AppDomainCntxType2 append(){return new AppDomainCntxType2(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_AppDomainCntx_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
	
	public MemberElement_QoISpatialCntxAttr QoISpatialCntxAttr;

		public static class MemberElement_QoISpatialCntxAttr
		{
			public static class MemberElement_QoISpatialCntxAttr_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_QoISpatialCntxAttr member;
				public MemberElement_QoISpatialCntxAttr_Iterator(MemberElement_QoISpatialCntxAttr member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					QoISpatialCntxAttrType nx = new QoISpatialCntxAttrType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_QoISpatialCntxAttr (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public QoISpatialCntxAttrType at(int index) {return new QoISpatialCntxAttrType(owner.getElementAt(info, index));}
			public QoISpatialCntxAttrType first() {return new QoISpatialCntxAttrType(owner.getElementFirst(info));}
			public QoISpatialCntxAttrType last(){return new QoISpatialCntxAttrType(owner.getElementLast(info));}
			public QoISpatialCntxAttrType append(){return new QoISpatialCntxAttrType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_QoISpatialCntxAttr_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
	
	public MemberElement_QoITemperalCntxAttr QoITemperalCntxAttr;

		public static class MemberElement_QoITemperalCntxAttr
		{
			public static class MemberElement_QoITemperalCntxAttr_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_QoITemperalCntxAttr member;
				public MemberElement_QoITemperalCntxAttr_Iterator(MemberElement_QoITemperalCntxAttr member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					QoITemperalCntxAttrType nx = new QoITemperalCntxAttrType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_QoITemperalCntxAttr (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public QoITemperalCntxAttrType at(int index) {return new QoITemperalCntxAttrType(owner.getElementAt(info, index));}
			public QoITemperalCntxAttrType first() {return new QoITemperalCntxAttrType(owner.getElementFirst(info));}
			public QoITemperalCntxAttrType last(){return new QoITemperalCntxAttrType(owner.getElementLast(info));}
			public QoITemperalCntxAttrType append(){return new QoITemperalCntxAttrType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_QoITemperalCntxAttr_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
}
