////////////////////////////////////////////////////////////////////////
//
// DataSourceQoIType.java
//
// This file was generated by XMLSpy 2014 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

package com.MetaData;

public class DataSourceQoIType extends com.altova.xml.TypeBase
{
	public static com.altova.xml.meta.ComplexType getStaticInfo() { return new com.altova.xml.meta.ComplexType(com.MetaData.MetaData_TypeInfo.binder.getTypes()[com.MetaData.MetaData_TypeInfo._altova_ti_altova_DataSourceQoIType]); }
	
	public DataSourceQoIType(org.w3c.dom.Node init)
	{
		super(init);
		instantiateMembers();
	}

	private void instantiateMembers()
	{

		QoIBaseAttr= new MemberElement_QoIBaseAttr (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_DataSourceQoIType._QoIBaseAttr]);
	}
	// Attributes


	// Elements
	
	public MemberElement_QoIBaseAttr QoIBaseAttr;

		public static class MemberElement_QoIBaseAttr
		{
			public static class MemberElement_QoIBaseAttr_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_QoIBaseAttr member;
				public MemberElement_QoIBaseAttr_Iterator(MemberElement_QoIBaseAttr member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					QoIBaseAttrType nx = new QoIBaseAttrType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_QoIBaseAttr (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public QoIBaseAttrType at(int index) {return new QoIBaseAttrType(owner.getElementAt(info, index));}
			public QoIBaseAttrType first() {return new QoIBaseAttrType(owner.getElementFirst(info));}
			public QoIBaseAttrType last(){return new QoIBaseAttrType(owner.getElementLast(info));}
			public QoIBaseAttrType append(){return new QoIBaseAttrType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_QoIBaseAttr_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
}
