////////////////////////////////////////////////////////////////////////
//
// MetaData_typeinfo.java
//
// This file was generated by XMLSpy 2014 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


package com.MetaData;

import com.altova.typeinfo.*;



public class MetaData_TypeInfo
{
	// namespaces indices
	public static final int _altova_ni = 0;
	public static final int _altova_ni_xs = 1;


	// typeinfo indices
	public static final int _altova_tif = 0 ;
	public static final int _altova_ti_altova_BaseMetric = _altova_tif ;
	public static final int _altova_ti_altova_Coordinate = 1 ;
	public static final int _altova_ti_altova_QoIMetric = 2 ;
	public static final int _altova_ti_altova_MetaData = 3 ;
	public static final int _altova_ti_altova_BaseDataType = 4 ;
	public static final int _altova_ti_altova_locationType = 5 ;
	public static final int _altova_ti_altova_BaseQoIType = 6 ;
	public static final int _altova_ti_altova_DataSourceType = 7 ;
	public static final int _altova_ti_altova_ContextType = 8 ;
	public static final int _altova_ti_altova_InformationQoIType = 9 ;
	public static final int _altova_ti_altova_QoIBaseAttrType = 10 ;
	public static final int _altova_ti_altova_BaseVoIType = 11 ;
	public static final int _altova_ti_altova_VoIBaseAttrType = 12 ;
	public static final int _altova_ti_altova_ContextType2 = 13 ;
	public static final int _altova_ti_altova_AppDomainCntxType = 14 ;
	public static final int _altova_ti_altova_ContactType = 15 ;
	public static final int _altova_ti_altova_InformationType = 16 ;
	public static final int _altova_ti_altova_EnumeratedMetricType = 17 ;
	public static final int _altova_ti_altova_QoIEnumeratedMetricType = 18 ;
	public static final int _altova_ti_altova_QoIQuantitativeMetricType = 19 ;
	public static final int _altova_ti_altova_SensorType = 20 ;
	public static final int _altova_ti_altova_identificationType = 21 ;
	public static final int _altova_ti_altova_classificationType = 22 ;
	public static final int _altova_ti_altova_validTimeType = 23 ;
	public static final int _altova_ti_altova_characteristicsType = 24 ;
	public static final int _altova_ti_altova_weightType = 25 ;
	public static final int _altova_ti_altova_heightType = 26 ;
	public static final int _altova_ti_altova_widthType = 27 ;
	public static final int _altova_ti_altova_materialType = 28 ;
	public static final int _altova_ti_altova_lengthType = 29 ;
	public static final int _altova_ti_altova_capabilitiesType = 30 ;
	public static final int _altova_ti_altova_sampleRateType = 31 ;
	public static final int _altova_ti_altova_batteryLifeType = 32 ;
	public static final int _altova_ti_altova_powerCurrentType = 33 ;
	public static final int _altova_ti_altova_ComponentsType = 34 ;
	public static final int _altova_ti_altova_componentType = 35 ;
	public static final int _altova_ti_altova_HumanType = 36 ;
	public static final int _altova_ti_altova_DataSourceQoIType = 37 ;
	public static final int _altova_ti_altova_AppDomainCntxType2 = 38 ;
	public static final int _altova_ti_altova_QoISpatialCntxAttrType = 39 ;
	public static final int _altova_ti_altova_QoITemperalCntxAttrType = 40 ;
	public static final int _altova_ti_altova_QoIIntegrityAttrType = 41 ;
	public static final int _altova_ti_altova_QoIAccuracyAttrType = 42 ;
	public static final int _altova_ti_altova_QoITimelinessAttrType = 43 ;
	public static final int _altova_ti_altova_QoIFormatAttrType = 44 ;
	public static final int _altova_ti_altova_VoIUsefulnessAttrType = 45 ;
	public static final int _altova_ti_altova_VoITrustAttrType = 46 ;
	public static final int _altova_ti_altova_VoIConvenienceAttrType = 47 ;
	public static final int _altova_til = 48 ;

	public static final int _altova_tif_xs = _altova_til;
	public static final int _altova_ti_xs_altova_ENTITIES = _altova_tif_xs ;
	public static final int _altova_ti_xs_altova_ENTITY = 49 ;
	public static final int _altova_ti_xs_altova_ID = 50 ;
	public static final int _altova_ti_xs_altova_IDREF = 51 ;
	public static final int _altova_ti_xs_altova_IDREFS = 52 ;
	public static final int _altova_ti_xs_altova_NCName = 53 ;
	public static final int _altova_ti_xs_altova_NMTOKEN = 54 ;
	public static final int _altova_ti_xs_altova_NMTOKENS = 55 ;
	public static final int _altova_ti_xs_altova_NOTATION = 56 ;
	public static final int _altova_ti_xs_altova_Name = 57 ;
	public static final int _altova_ti_xs_altova_QName = 58 ;
	public static final int _altova_ti_xs_altova_anySimpleType = 59 ;
	public static final int _altova_ti_xs_altova_anyType = 60 ;
	public static final int _altova_ti_xs_altova_anyURI = 61 ;
	public static final int _altova_ti_xs_altova_base64Binary = 62 ;
	public static final int _altova_ti_xs_altova_boolean2 = 63 ;
	public static final int _altova_ti_xs_altova_byte2 = 64 ;
	public static final int _altova_ti_xs_altova_date = 65 ;
	public static final int _altova_ti_xs_altova_dateTime = 66 ;
	public static final int _altova_ti_xs_altova_decimal = 67 ;
	public static final int _altova_ti_xs_altova_double2 = 68 ;
	public static final int _altova_ti_xs_altova_duration = 69 ;
	public static final int _altova_ti_xs_altova_float2 = 70 ;
	public static final int _altova_ti_xs_altova_gDay = 71 ;
	public static final int _altova_ti_xs_altova_gMonth = 72 ;
	public static final int _altova_ti_xs_altova_gMonthDay = 73 ;
	public static final int _altova_ti_xs_altova_gYear = 74 ;
	public static final int _altova_ti_xs_altova_gYearMonth = 75 ;
	public static final int _altova_ti_xs_altova_hexBinary = 76 ;
	public static final int _altova_ti_xs_altova_int2 = 77 ;
	public static final int _altova_ti_xs_altova_integer = 78 ;
	public static final int _altova_ti_xs_altova_language = 79 ;
	public static final int _altova_ti_xs_altova_long2 = 80 ;
	public static final int _altova_ti_xs_altova_negativeInteger = 81 ;
	public static final int _altova_ti_xs_altova_nonNegativeInteger = 82 ;
	public static final int _altova_ti_xs_altova_nonPositiveInteger = 83 ;
	public static final int _altova_ti_xs_altova_normalizedString = 84 ;
	public static final int _altova_ti_xs_altova_positiveInteger = 85 ;
	public static final int _altova_ti_xs_altova_short2 = 86 ;
	public static final int _altova_ti_xs_altova_string2 = 87 ;
	public static final int _altova_ti_xs_altova_time = 88 ;
	public static final int _altova_ti_xs_altova_token = 89 ;
	public static final int _altova_ti_xs_altova_unsignedByte = 90 ;
	public static final int _altova_ti_xs_altova_unsignedInt = 91 ;
	public static final int _altova_ti_xs_altova_unsignedLong = 92 ;
	public static final int _altova_ti_xs_altova_unsignedShort = 93 ;
	public static final int _altova_ti_xs_altova_doubleType = 94 ;
	public static final int _altova_ti_xs_altova_dateTimeType = 95 ;
	public static final int _altova_ti_xs_altova_stringType = 96 ;
	public static final int _altova_til_xs = 97 ;



	// memberinfo indices

	public static class _altova_mi_altova_BaseMetric {
		public static final int begin = 0 ;
		public static final int _EnumeratedMetric = _altova_mi_altova_BaseMetric.begin ;
		public static final int _QuantitativeMetric = 1 ;
		public static final int end = 2 ;
	};


	public static class _altova_mi_altova_Coordinate {
		public static final int begin = _altova_mi_altova_BaseMetric.end ;
		public static final int _latitude = _altova_mi_altova_Coordinate.begin ;
		public static final int _longitude = 3 ;
		public static final int _depth = 4 ;
		public static final int _orientation = 5 ;
		public static final int end = 6 ;
	};


	public static class _altova_mi_altova_QoIMetric {
		public static final int begin = _altova_mi_altova_Coordinate.end ;
		public static final int _name = _altova_mi_altova_QoIMetric.begin ;
		public static final int _QoIEnumeratedMetric = 7 ;
		public static final int _QoIQuantitativeMetric = 8 ;
		public static final int end = 9 ;
	};


	public static class _altova_mi_altova_MetaData {
		public static final int begin = _altova_mi_altova_QoIMetric.end ;
		public static final int _BaseData = _altova_mi_altova_MetaData.begin ;
		public static final int _BaseQoI = 10 ;
		public static final int _BaseVoI = 11 ;
		public static final int _Contact = 12 ;
		public static final int _Context = 13 ;
		public static final int _DataSource = 14 ;
		public static final int _Information = 15 ;
		public static final int _QoIBaseAttr = 16 ;
		public static final int _VoIBaseAttr = 17 ;
		public static final int end = 18 ;
	};


	public static class _altova_mi_altova_BaseDataType {
		public static final int begin = _altova_mi_altova_MetaData.end ;
		public static final int _metric = _altova_mi_altova_BaseDataType.begin ;
		public static final int _location = 19 ;
		public static final int _dateTime = 20 ;
		public static final int end = 21 ;
	};


	public static class _altova_mi_altova_locationType {
		public static final int begin = _altova_mi_altova_BaseDataType.end ;
		public static final int _lon = _altova_mi_altova_locationType.begin ;
		public static final int _lat = 22 ;
		public static final int end = 23 ;
	};


	public static class _altova_mi_altova_BaseQoIType {
		public static final int begin = _altova_mi_altova_locationType.end ;
		public static final int _DataSource = _altova_mi_altova_BaseQoIType.begin ;
		public static final int _Context = 24 ;
		public static final int _InformationQoI = 25 ;
		public static final int end = 26 ;
	};


	public static class _altova_mi_altova_DataSourceType {
		public static final int begin = _altova_mi_altova_BaseQoIType.end ;
		public static final int _id = _altova_mi_altova_DataSourceType.begin ;
		public static final int _publishDate = 27 ;
		public static final int _role = 28 ;
		public static final int _isOwnedBy = 29 ;
		public static final int _publisher = 30 ;
		public static final int _Sensor = 31 ;
		public static final int _Human = 32 ;
		public static final int _DataSourceQoI = 33 ;
		public static final int end = 34 ;
	};


	public static class _altova_mi_altova_ContextType {
		public static final int begin = _altova_mi_altova_DataSourceType.end ;
		public static final int _AppDomainCntx = _altova_mi_altova_ContextType.begin ;
		public static final int _QoISpatialCntxAttr = 35 ;
		public static final int _QoITemperalCntxAttr = 36 ;
		public static final int end = 37 ;
	};


	public static class _altova_mi_altova_InformationQoIType {
		public static final int begin = _altova_mi_altova_ContextType.end ;
		public static final int _id = _altova_mi_altova_InformationQoIType.begin ;
		public static final int _QoIBaseAttr = 38 ;
		public static final int end = 39 ;
	};


	public static class _altova_mi_altova_QoIBaseAttrType {
		public static final int begin = _altova_mi_altova_InformationQoIType.end ;
		public static final int _name = _altova_mi_altova_QoIBaseAttrType.begin ;
		public static final int _id = 40 ;
		public static final int _QoIIntegrityAttr = 41 ;
		public static final int _QoIAccuracyAttr = 42 ;
		public static final int _QoITimelinessAttr = 43 ;
		public static final int _QoIFormatAttr = 44 ;
		public static final int end = 45 ;
	};


	public static class _altova_mi_altova_BaseVoIType {
		public static final int begin = _altova_mi_altova_QoIBaseAttrType.end ;
		public static final int _VoIBaseAttr = _altova_mi_altova_BaseVoIType.begin ;
		public static final int _Context = 46 ;
		public static final int end = 47 ;
	};


	public static class _altova_mi_altova_VoIBaseAttrType {
		public static final int begin = _altova_mi_altova_BaseVoIType.end ;
		public static final int _name = _altova_mi_altova_VoIBaseAttrType.begin ;
		public static final int _id = 48 ;
		public static final int _VoIUsefulnessAttr = 49 ;
		public static final int _VoITrustAttr = 50 ;
		public static final int _VoIConvenienceAttr = 51 ;
		public static final int end = 52 ;
	};


	public static class _altova_mi_altova_ContextType2 {
		public static final int begin = _altova_mi_altova_VoIBaseAttrType.end ;
		public static final int _AppDomainCntx = _altova_mi_altova_ContextType2.begin ;
		public static final int end = 53 ;
	};


	public static class _altova_mi_altova_AppDomainCntxType {
		public static final int begin = _altova_mi_altova_ContextType2.end ;
		public static final int _description = _altova_mi_altova_AppDomainCntxType.begin ;
		public static final int _name = 54 ;
		public static final int _standardName = 55 ;
		public static final int _standardDescription = 56 ;
		public static final int end = 57 ;
	};


	public static class _altova_mi_altova_ContactType {
		public static final int begin = _altova_mi_altova_AppDomainCntxType.end ;
		public static final int _name = _altova_mi_altova_ContactType.begin ;
		public static final int _organization = 58 ;
		public static final int _position = 59 ;
		public static final int _phone = 60 ;
		public static final int _email = 61 ;
		public static final int _eid = 62 ;
		public static final int end = 63 ;
	};


	public static class _altova_mi_altova_InformationType {
		public static final int begin = _altova_mi_altova_ContactType.end ;
		public static final int _id = _altova_mi_altova_InformationType.begin ;
		public static final int _type = 64 ;
		public static final int _BaseQoI = 65 ;
		public static final int _BaseVoI = 66 ;
		public static final int _BaseData = 67 ;
		public static final int end = 68 ;
	};


	public static class _altova_mi_altova_EnumeratedMetricType {
		public static final int begin = _altova_mi_altova_InformationType.end ;
		public static final int _selectedValue = _altova_mi_altova_EnumeratedMetricType.begin ;
		public static final int _permissibleValues = 69 ;
		public static final int end = 70 ;
	};


	public static class _altova_mi_altova_QoIEnumeratedMetricType {
		public static final int begin = _altova_mi_altova_EnumeratedMetricType.end ;
		public static final int _selectedValue = _altova_mi_altova_QoIEnumeratedMetricType.begin ;
		public static final int _permissibleValues = 71 ;
		public static final int end = 72 ;
	};


	public static class _altova_mi_altova_QoIQuantitativeMetricType {
		public static final int begin = _altova_mi_altova_QoIEnumeratedMetricType.end ;
		public static final int _uofm = _altova_mi_altova_QoIQuantitativeMetricType.begin ;
		public static final int _errorRange = 73 ;
		public static final int _biasError = 74 ;
		public static final int end = 75 ;
	};


	public static class _altova_mi_altova_SensorType {
		public static final int begin = _altova_mi_altova_QoIQuantitativeMetricType.end ;
		public static final int _Contact = _altova_mi_altova_SensorType.begin ;
		public static final int _identification = 76 ;
		public static final int _classification = 77 ;
		public static final int _validTime = 78 ;
		public static final int _characteristics = 79 ;
		public static final int _capabilities = 80 ;
		public static final int _Components = 81 ;
		public static final int end = 82 ;
	};


	public static class _altova_mi_altova_identificationType {
		public static final int begin = _altova_mi_altova_SensorType.end ;
		public static final int _uid = _altova_mi_altova_identificationType.begin ;
		public static final int _shortName = 83 ;
		public static final int _longName = 84 ;
		public static final int _manufacturer = 85 ;
		public static final int _modelNumber = 86 ;
		public static final int _deviceId = 87 ;
		public static final int end = 88 ;
	};


	public static class _altova_mi_altova_classificationType {
		public static final int begin = _altova_mi_altova_identificationType.end ;
		public static final int _sensorType2 = _altova_mi_altova_classificationType.begin ;
		public static final int end = 89 ;
	};


	public static class _altova_mi_altova_validTimeType {
		public static final int begin = _altova_mi_altova_classificationType.end ;
		public static final int _start = _altova_mi_altova_validTimeType.begin ;
		public static final int _end = 90 ;
		public static final int end = 91 ;
	};


	public static class _altova_mi_altova_characteristicsType {
		public static final int begin = _altova_mi_altova_validTimeType.end ;
		public static final int _weight = _altova_mi_altova_characteristicsType.begin ;
		public static final int _height = 92 ;
		public static final int _width = 93 ;
		public static final int _material = 94 ;
		public static final int _length = 95 ;
		public static final int end = 96 ;
	};


	public static class _altova_mi_altova_weightType {
		public static final int begin = _altova_mi_altova_characteristicsType.end ;
		public static final int _uofm = _altova_mi_altova_weightType.begin ;
		public static final int end = 97 ;
	};


	public static class _altova_mi_altova_heightType {
		public static final int begin = _altova_mi_altova_weightType.end ;
		public static final int _uofm = _altova_mi_altova_heightType.begin ;
		public static final int end = 98 ;
	};


	public static class _altova_mi_altova_widthType {
		public static final int begin = _altova_mi_altova_heightType.end ;
		public static final int _uofm = _altova_mi_altova_widthType.begin ;
		public static final int end = 99 ;
	};


	public static class _altova_mi_altova_materialType {
		public static final int begin = _altova_mi_altova_widthType.end ;
		public static final int _uofm = _altova_mi_altova_materialType.begin ;
		public static final int end = 100 ;
	};


	public static class _altova_mi_altova_lengthType {
		public static final int begin = _altova_mi_altova_materialType.end ;
		public static final int _uofm = _altova_mi_altova_lengthType.begin ;
		public static final int end = 101 ;
	};


	public static class _altova_mi_altova_capabilitiesType {
		public static final int begin = _altova_mi_altova_lengthType.end ;
		public static final int _sampleRate = _altova_mi_altova_capabilitiesType.begin ;
		public static final int _batteryLife = 102 ;
		public static final int _powerCurrent = 103 ;
		public static final int end = 104 ;
	};


	public static class _altova_mi_altova_sampleRateType {
		public static final int begin = _altova_mi_altova_capabilitiesType.end ;
		public static final int _uofm = _altova_mi_altova_sampleRateType.begin ;
		public static final int end = 105 ;
	};


	public static class _altova_mi_altova_batteryLifeType {
		public static final int begin = _altova_mi_altova_sampleRateType.end ;
		public static final int _uofm = _altova_mi_altova_batteryLifeType.begin ;
		public static final int end = 106 ;
	};


	public static class _altova_mi_altova_powerCurrentType {
		public static final int begin = _altova_mi_altova_batteryLifeType.end ;
		public static final int _uofm = _altova_mi_altova_powerCurrentType.begin ;
		public static final int end = 107 ;
	};


	public static class _altova_mi_altova_ComponentsType {
		public static final int begin = _altova_mi_altova_powerCurrentType.end ;
		public static final int _component = _altova_mi_altova_ComponentsType.begin ;
		public static final int end = 108 ;
	};


	public static class _altova_mi_altova_componentType {
		public static final int begin = _altova_mi_altova_ComponentsType.end ;
		public static final int end = _altova_mi_altova_componentType.begin ;
	};


	public static class _altova_mi_altova_HumanType {
		public static final int begin = _altova_mi_altova_componentType.end ;
		public static final int _Contact = _altova_mi_altova_HumanType.begin ;
		public static final int end = 109 ;
	};


	public static class _altova_mi_altova_DataSourceQoIType {
		public static final int begin = _altova_mi_altova_HumanType.end ;
		public static final int _QoIBaseAttr = _altova_mi_altova_DataSourceQoIType.begin ;
		public static final int end = 110 ;
	};


	public static class _altova_mi_altova_AppDomainCntxType2 {
		public static final int begin = _altova_mi_altova_DataSourceQoIType.end ;
		public static final int _description = _altova_mi_altova_AppDomainCntxType2.begin ;
		public static final int _name = 111 ;
		public static final int _standardName = 112 ;
		public static final int _standardDescription = 113 ;
		public static final int end = 114 ;
	};


	public static class _altova_mi_altova_QoISpatialCntxAttrType {
		public static final int begin = _altova_mi_altova_AppDomainCntxType2.end ;
		public static final int _name = _altova_mi_altova_QoISpatialCntxAttrType.begin ;
		public static final int _lowerBound = 115 ;
		public static final int _upperBound = 116 ;
		public static final int end = 117 ;
	};


	public static class _altova_mi_altova_QoITemperalCntxAttrType {
		public static final int begin = _altova_mi_altova_QoISpatialCntxAttrType.end ;
		public static final int _name = _altova_mi_altova_QoITemperalCntxAttrType.begin ;
		public static final int _startTime = 118 ;
		public static final int _endTime = 119 ;
		public static final int _lowerBound = 120 ;
		public static final int _upperBound = 121 ;
		public static final int _eventType = 122 ;
		public static final int end = 123 ;
	};


	public static class _altova_mi_altova_QoIIntegrityAttrType {
		public static final int begin = _altova_mi_altova_QoITemperalCntxAttrType.end ;
		public static final int _sourceIntegrity = _altova_mi_altova_QoIIntegrityAttrType.begin ;
		public static final int _channelIntegrity = 124 ;
		public static final int _auditability = 125 ;
		public static final int _attestability = 126 ;
		public static final int _confidentiality = 127 ;
		public static final int end = 128 ;
	};


	public static class _altova_mi_altova_QoIAccuracyAttrType {
		public static final int begin = _altova_mi_altova_QoIIntegrityAttrType.end ;
		public static final int _volatility = _altova_mi_altova_QoIAccuracyAttrType.begin ;
		public static final int _detailLevel = 129 ;
		public static final int _volume = 130 ;
		public static final int _consistency = 131 ;
		public static final int _resolution = 132 ;
		public static final int _bias = 133 ;
		public static final int _errorLevel = 134 ;
		public static final int _errorRate = 135 ;
		public static final int end = 136 ;
	};


	public static class _altova_mi_altova_QoITimelinessAttrType {
		public static final int begin = _altova_mi_altova_QoIAccuracyAttrType.end ;
		public static final int _latencySource = _altova_mi_altova_QoITimelinessAttrType.begin ;
		public static final int _detailLevel = 137 ;
		public static final int _validityExpiration = 138 ;
		public static final int _timelinessLevel = 139 ;
		public static final int end = 140 ;
	};


	public static class _altova_mi_altova_QoIFormatAttrType {
		public static final int begin = _altova_mi_altova_QoITimelinessAttrType.end ;
		public static final int _encoding = _altova_mi_altova_QoIFormatAttrType.begin ;
		public static final int _conciseness = 141 ;
		public static final int end = 142 ;
	};


	public static class _altova_mi_altova_VoIUsefulnessAttrType {
		public static final int begin = _altova_mi_altova_QoIFormatAttrType.end ;
		public static final int _novelty = _altova_mi_altova_VoIUsefulnessAttrType.begin ;
		public static final int _revelance = 143 ;
		public static final int _timeliness = 144 ;
		public static final int _completeness = 145 ;
		public static final int end = 146 ;
	};


	public static class _altova_mi_altova_VoITrustAttrType {
		public static final int begin = _altova_mi_altova_VoIUsefulnessAttrType.end ;
		public static final int _sourceReputation = _altova_mi_altova_VoITrustAttrType.begin ;
		public static final int _channelReputation = 147 ;
		public static final int _sourceObjectivity = 148 ;
		public static final int end = 149 ;
	};


	public static class _altova_mi_altova_VoIConvenienceAttrType {
		public static final int begin = _altova_mi_altova_VoITrustAttrType.end ;
		public static final int _easeOfUse = _altova_mi_altova_VoIConvenienceAttrType.begin ;
		public static final int _formatCompatibility = 150 ;
		public static final int _composability = 151 ;
		public static final int end = 152 ;
	};


	public static class _altova_mi_xs_altova_ENTITIES {
		public static final int begin = _altova_mi_altova_VoIConvenienceAttrType.end ;
		public static final int end = _altova_mi_xs_altova_ENTITIES.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITY {
		public static final int begin = _altova_mi_xs_altova_ENTITIES.end ;
		public static final int end = _altova_mi_xs_altova_ENTITY.begin ;
	};


	public static class _altova_mi_xs_altova_ID {
		public static final int begin = _altova_mi_xs_altova_ENTITY.end ;
		public static final int end = _altova_mi_xs_altova_ID.begin ;
	};


	public static class _altova_mi_xs_altova_IDREF {
		public static final int begin = _altova_mi_xs_altova_ID.end ;
		public static final int end = _altova_mi_xs_altova_IDREF.begin ;
	};


	public static class _altova_mi_xs_altova_IDREFS {
		public static final int begin = _altova_mi_xs_altova_IDREF.end ;
		public static final int end = _altova_mi_xs_altova_IDREFS.begin ;
	};


	public static class _altova_mi_xs_altova_NCName {
		public static final int begin = _altova_mi_xs_altova_IDREFS.end ;
		public static final int end = _altova_mi_xs_altova_NCName.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKEN {
		public static final int begin = _altova_mi_xs_altova_NCName.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKEN.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKENS {
		public static final int begin = _altova_mi_xs_altova_NMTOKEN.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKENS.begin ;
	};


	public static class _altova_mi_xs_altova_NOTATION {
		public static final int begin = _altova_mi_xs_altova_NMTOKENS.end ;
		public static final int end = _altova_mi_xs_altova_NOTATION.begin ;
	};


	public static class _altova_mi_xs_altova_Name {
		public static final int begin = _altova_mi_xs_altova_NOTATION.end ;
		public static final int end = _altova_mi_xs_altova_Name.begin ;
	};


	public static class _altova_mi_xs_altova_QName {
		public static final int begin = _altova_mi_xs_altova_Name.end ;
		public static final int end = _altova_mi_xs_altova_QName.begin ;
	};


	public static class _altova_mi_xs_altova_anySimpleType {
		public static final int begin = _altova_mi_xs_altova_QName.end ;
		public static final int end = _altova_mi_xs_altova_anySimpleType.begin ;
	};


	public static class _altova_mi_xs_altova_anyType {
		public static final int begin = _altova_mi_xs_altova_anySimpleType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_anyType.begin ;
		public static final int end = 153 ;
	};


	public static class _altova_mi_xs_altova_anyURI {
		public static final int begin = _altova_mi_xs_altova_anyType.end ;
		public static final int end = _altova_mi_xs_altova_anyURI.begin ;
	};


	public static class _altova_mi_xs_altova_base64Binary {
		public static final int begin = _altova_mi_xs_altova_anyURI.end ;
		public static final int end = _altova_mi_xs_altova_base64Binary.begin ;
	};


	public static class _altova_mi_xs_altova_boolean2 {
		public static final int begin = _altova_mi_xs_altova_base64Binary.end ;
		public static final int end = _altova_mi_xs_altova_boolean2.begin ;
	};


	public static class _altova_mi_xs_altova_byte2 {
		public static final int begin = _altova_mi_xs_altova_boolean2.end ;
		public static final int end = _altova_mi_xs_altova_byte2.begin ;
	};


	public static class _altova_mi_xs_altova_date {
		public static final int begin = _altova_mi_xs_altova_byte2.end ;
		public static final int end = _altova_mi_xs_altova_date.begin ;
	};


	public static class _altova_mi_xs_altova_dateTime {
		public static final int begin = _altova_mi_xs_altova_date.end ;
		public static final int end = _altova_mi_xs_altova_dateTime.begin ;
	};


	public static class _altova_mi_xs_altova_decimal {
		public static final int begin = _altova_mi_xs_altova_dateTime.end ;
		public static final int end = _altova_mi_xs_altova_decimal.begin ;
	};


	public static class _altova_mi_xs_altova_double2 {
		public static final int begin = _altova_mi_xs_altova_decimal.end ;
		public static final int end = _altova_mi_xs_altova_double2.begin ;
	};


	public static class _altova_mi_xs_altova_duration {
		public static final int begin = _altova_mi_xs_altova_double2.end ;
		public static final int end = _altova_mi_xs_altova_duration.begin ;
	};


	public static class _altova_mi_xs_altova_float2 {
		public static final int begin = _altova_mi_xs_altova_duration.end ;
		public static final int end = _altova_mi_xs_altova_float2.begin ;
	};


	public static class _altova_mi_xs_altova_gDay {
		public static final int begin = _altova_mi_xs_altova_float2.end ;
		public static final int end = _altova_mi_xs_altova_gDay.begin ;
	};


	public static class _altova_mi_xs_altova_gMonth {
		public static final int begin = _altova_mi_xs_altova_gDay.end ;
		public static final int end = _altova_mi_xs_altova_gMonth.begin ;
	};


	public static class _altova_mi_xs_altova_gMonthDay {
		public static final int begin = _altova_mi_xs_altova_gMonth.end ;
		public static final int end = _altova_mi_xs_altova_gMonthDay.begin ;
	};


	public static class _altova_mi_xs_altova_gYear {
		public static final int begin = _altova_mi_xs_altova_gMonthDay.end ;
		public static final int end = _altova_mi_xs_altova_gYear.begin ;
	};


	public static class _altova_mi_xs_altova_gYearMonth {
		public static final int begin = _altova_mi_xs_altova_gYear.end ;
		public static final int end = _altova_mi_xs_altova_gYearMonth.begin ;
	};


	public static class _altova_mi_xs_altova_hexBinary {
		public static final int begin = _altova_mi_xs_altova_gYearMonth.end ;
		public static final int end = _altova_mi_xs_altova_hexBinary.begin ;
	};


	public static class _altova_mi_xs_altova_int2 {
		public static final int begin = _altova_mi_xs_altova_hexBinary.end ;
		public static final int end = _altova_mi_xs_altova_int2.begin ;
	};


	public static class _altova_mi_xs_altova_integer {
		public static final int begin = _altova_mi_xs_altova_int2.end ;
		public static final int end = _altova_mi_xs_altova_integer.begin ;
	};


	public static class _altova_mi_xs_altova_language {
		public static final int begin = _altova_mi_xs_altova_integer.end ;
		public static final int end = _altova_mi_xs_altova_language.begin ;
	};


	public static class _altova_mi_xs_altova_long2 {
		public static final int begin = _altova_mi_xs_altova_language.end ;
		public static final int end = _altova_mi_xs_altova_long2.begin ;
	};


	public static class _altova_mi_xs_altova_negativeInteger {
		public static final int begin = _altova_mi_xs_altova_long2.end ;
		public static final int end = _altova_mi_xs_altova_negativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonNegativeInteger {
		public static final int begin = _altova_mi_xs_altova_negativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonNegativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonPositiveInteger {
		public static final int begin = _altova_mi_xs_altova_nonNegativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonPositiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_normalizedString {
		public static final int begin = _altova_mi_xs_altova_nonPositiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_normalizedString.begin ;
	};


	public static class _altova_mi_xs_altova_positiveInteger {
		public static final int begin = _altova_mi_xs_altova_normalizedString.end ;
		public static final int end = _altova_mi_xs_altova_positiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_short2 {
		public static final int begin = _altova_mi_xs_altova_positiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_short2.begin ;
	};


	public static class _altova_mi_xs_altova_string2 {
		public static final int begin = _altova_mi_xs_altova_short2.end ;
		public static final int end = _altova_mi_xs_altova_string2.begin ;
	};


	public static class _altova_mi_xs_altova_time {
		public static final int begin = _altova_mi_xs_altova_string2.end ;
		public static final int end = _altova_mi_xs_altova_time.begin ;
	};


	public static class _altova_mi_xs_altova_token {
		public static final int begin = _altova_mi_xs_altova_time.end ;
		public static final int end = _altova_mi_xs_altova_token.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedByte {
		public static final int begin = _altova_mi_xs_altova_token.end ;
		public static final int end = _altova_mi_xs_altova_unsignedByte.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedInt {
		public static final int begin = _altova_mi_xs_altova_unsignedByte.end ;
		public static final int end = _altova_mi_xs_altova_unsignedInt.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedLong {
		public static final int begin = _altova_mi_xs_altova_unsignedInt.end ;
		public static final int end = _altova_mi_xs_altova_unsignedLong.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedShort {
		public static final int begin = _altova_mi_xs_altova_unsignedLong.end ;
		public static final int end = _altova_mi_xs_altova_unsignedShort.begin ;
	};


	public static class _altova_mi_xs_altova_doubleType {
		public static final int begin = _altova_mi_xs_altova_unsignedShort.end ;
		public static final int _unnamed = _altova_mi_xs_altova_doubleType.begin ;
		public static final int end = 154 ;
	};


	public static class _altova_mi_xs_altova_dateTimeType {
		public static final int begin = _altova_mi_xs_altova_doubleType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_dateTimeType.begin ;
		public static final int end = 155 ;
	};


	public static class _altova_mi_xs_altova_stringType {
		public static final int begin = _altova_mi_xs_altova_dateTimeType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_stringType.begin ;
		public static final int end = 156 ;
	};

	

	public static class InfoBinder implements InfoBinderInterface
	{
		public NamespaceInfo[] getNamespaces() {return namespaces;}
		public TypeInfo[] getTypes() {return types;}
		public MemberInfo[] getMembers() {return members;}
	}
	
	public static InfoBinderInterface binder = new InfoBinder();

	// Array of all namespaces with pointers to types:
	public static final NamespaceInfo namespaces[] = 
	{
		new NamespaceInfo(binder, "", "", _altova_tif, _altova_til),
		new NamespaceInfo(binder, "http://www.w3.org/2001/XMLSchema", "xs", _altova_tif_xs, _altova_til_xs),
	};

	
// Array of all types with pointers to members:
	public static final TypeInfo types[] = new TypeInfoCreator().createTypes(binder);

	private static class TypeInfoCreator
	{
		private void initTypes0(InfoBinderInterface binder, TypeInfo[] types) {
			types[0] = new TypeInfo( binder, _altova_ni, "BaseMetric", _altova_ti_xs_altova_anyType, _altova_mi_altova_BaseMetric.begin, _altova_mi_altova_BaseMetric.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[1] = new TypeInfo( binder, _altova_ni, "Coordinate", _altova_ti_xs_altova_anyType, _altova_mi_altova_Coordinate.begin, _altova_mi_altova_Coordinate.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[2] = new TypeInfo( binder, _altova_ni, "QoIMetric", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoIMetric.begin, _altova_mi_altova_QoIMetric.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[3] = new TypeInfo( binder, _altova_ni, "MetaData", 0, _altova_mi_altova_MetaData.begin, _altova_mi_altova_MetaData.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[4] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BaseDataType.begin, _altova_mi_altova_BaseDataType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[5] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_locationType.begin, _altova_mi_altova_locationType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[6] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BaseQoIType.begin, _altova_mi_altova_BaseQoIType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[7] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_DataSourceType.begin, _altova_mi_altova_DataSourceType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[8] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_ContextType.begin, _altova_mi_altova_ContextType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[9] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_InformationQoIType.begin, _altova_mi_altova_InformationQoIType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[10] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoIBaseAttrType.begin, _altova_mi_altova_QoIBaseAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[11] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BaseVoIType.begin, _altova_mi_altova_BaseVoIType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[12] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_VoIBaseAttrType.begin, _altova_mi_altova_VoIBaseAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[13] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_ContextType2.begin, _altova_mi_altova_ContextType2.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[14] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_AppDomainCntxType.begin, _altova_mi_altova_AppDomainCntxType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[15] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_ContactType.begin, _altova_mi_altova_ContactType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[16] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_InformationType.begin, _altova_mi_altova_InformationType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[17] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_EnumeratedMetricType.begin, _altova_mi_altova_EnumeratedMetricType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[18] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoIEnumeratedMetricType.begin, _altova_mi_altova_QoIEnumeratedMetricType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[19] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoIQuantitativeMetricType.begin, _altova_mi_altova_QoIQuantitativeMetricType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[20] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_SensorType.begin, _altova_mi_altova_SensorType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[21] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_identificationType.begin, _altova_mi_altova_identificationType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[22] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_classificationType.begin, _altova_mi_altova_classificationType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[23] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_validTimeType.begin, _altova_mi_altova_validTimeType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[24] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_characteristicsType.begin, _altova_mi_altova_characteristicsType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[25] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_weightType.begin, _altova_mi_altova_weightType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[26] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_heightType.begin, _altova_mi_altova_heightType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[27] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_widthType.begin, _altova_mi_altova_widthType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[28] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_materialType.begin, _altova_mi_altova_materialType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[29] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_lengthType.begin, _altova_mi_altova_lengthType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[30] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_capabilitiesType.begin, _altova_mi_altova_capabilitiesType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[31] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_sampleRateType.begin, _altova_mi_altova_sampleRateType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[32] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_batteryLifeType.begin, _altova_mi_altova_batteryLifeType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[33] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_powerCurrentType.begin, _altova_mi_altova_powerCurrentType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[34] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_ComponentsType.begin, _altova_mi_altova_ComponentsType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[35] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_componentType.begin, _altova_mi_altova_componentType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[36] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_HumanType.begin, _altova_mi_altova_HumanType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[37] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_DataSourceQoIType.begin, _altova_mi_altova_DataSourceQoIType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[38] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_AppDomainCntxType2.begin, _altova_mi_altova_AppDomainCntxType2.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[39] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoISpatialCntxAttrType.begin, _altova_mi_altova_QoISpatialCntxAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[40] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoITemperalCntxAttrType.begin, _altova_mi_altova_QoITemperalCntxAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[41] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoIIntegrityAttrType.begin, _altova_mi_altova_QoIIntegrityAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[42] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoIAccuracyAttrType.begin, _altova_mi_altova_QoIAccuracyAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[43] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoITimelinessAttrType.begin, _altova_mi_altova_QoITimelinessAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[44] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_QoIFormatAttrType.begin, _altova_mi_altova_QoIFormatAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[45] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_VoIUsefulnessAttrType.begin, _altova_mi_altova_VoIUsefulnessAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[46] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_VoITrustAttrType.begin, _altova_mi_altova_VoITrustAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[47] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_VoIConvenienceAttrType.begin, _altova_mi_altova_VoIConvenienceAttrType.end,  null, 				WhitespaceType.Whitespace_Unknown );

			types[48] = new TypeInfo( binder, _altova_ni_xs, "ENTITIES", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_ENTITIES.begin, _altova_mi_xs_altova_ENTITIES.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[49] = new TypeInfo( binder, _altova_ni_xs, "ENTITY", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ENTITY.begin, _altova_mi_xs_altova_ENTITY.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[50] = new TypeInfo( binder, _altova_ni_xs, "ID", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ID.begin, _altova_mi_xs_altova_ID.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[51] = new TypeInfo( binder, _altova_ni_xs, "IDREF", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_IDREF.begin, _altova_mi_xs_altova_IDREF.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[52] = new TypeInfo( binder, _altova_ni_xs, "IDREFS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_IDREFS.begin, _altova_mi_xs_altova_IDREFS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[53] = new TypeInfo( binder, _altova_ni_xs, "NCName", _altova_ti_xs_altova_Name, _altova_mi_xs_altova_NCName.begin, _altova_mi_xs_altova_NCName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[54] = new TypeInfo( binder, _altova_ni_xs, "NMTOKEN", _altova_ti_xs_altova_token, _altova_mi_xs_altova_NMTOKEN.begin, _altova_mi_xs_altova_NMTOKEN.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[55] = new TypeInfo( binder, _altova_ni_xs, "NMTOKENS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NMTOKENS.begin, _altova_mi_xs_altova_NMTOKENS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[56] = new TypeInfo( binder, _altova_ni_xs, "NOTATION", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NOTATION.begin, _altova_mi_xs_altova_NOTATION.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[57] = new TypeInfo( binder, _altova_ni_xs, "Name", _altova_ti_xs_altova_token, _altova_mi_xs_altova_Name.begin, _altova_mi_xs_altova_Name.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "pattern", "\\i\\c*", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[58] = new TypeInfo( binder, _altova_ni_xs, "QName", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_QName.begin, _altova_mi_xs_altova_QName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[59] = new TypeInfo( binder, _altova_ni_xs, "anySimpleType", 0, _altova_mi_xs_altova_anySimpleType.begin, _altova_mi_xs_altova_anySimpleType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[60] = new TypeInfo( binder, _altova_ni_xs, "anyType", 0, _altova_mi_xs_altova_anyType.begin, _altova_mi_xs_altova_anyType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[61] = new TypeInfo( binder, _altova_ni_xs, "anyURI", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_anyURI.begin, _altova_mi_xs_altova_anyURI.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[62] = new TypeInfo( binder, _altova_ni_xs, "base64Binary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_base64Binary.begin, _altova_mi_xs_altova_base64Binary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[63] = new TypeInfo( binder, _altova_ni_xs, "boolean", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_boolean2.begin, _altova_mi_xs_altova_boolean2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[64] = new TypeInfo( binder, _altova_ni_xs, "byte", _altova_ti_xs_altova_short2, _altova_mi_xs_altova_byte2.begin, _altova_mi_xs_altova_byte2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "-128", 0 ), 
					new FacetInfo (null, "maxInclusive", "127", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[65] = new TypeInfo( binder, _altova_ni_xs, "date", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_date.begin, _altova_mi_xs_altova_date.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DateFormatter );
			types[66] = new TypeInfo( binder, _altova_ni_xs, "dateTime", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_dateTime.begin, _altova_mi_xs_altova_dateTime.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DateTimeFormatter );
			types[67] = new TypeInfo( binder, _altova_ni_xs, "decimal", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_decimal.begin, _altova_mi_xs_altova_decimal.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DecimalFormatter );
			types[68] = new TypeInfo( binder, _altova_ni_xs, "double", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_double2.begin, _altova_mi_xs_altova_double2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DoubleFormatter );
			types[69] = new TypeInfo( binder, _altova_ni_xs, "duration", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_duration.begin, _altova_mi_xs_altova_duration.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DurationFormatter );
			types[70] = new TypeInfo( binder, _altova_ni_xs, "float", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_float2.begin, _altova_mi_xs_altova_float2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DoubleFormatter );
			types[71] = new TypeInfo( binder, _altova_ni_xs, "gDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gDay.begin, _altova_mi_xs_altova_gDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GDayFormatter );
			types[72] = new TypeInfo( binder, _altova_ni_xs, "gMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonth.begin, _altova_mi_xs_altova_gMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GMonthFormatter );
			types[73] = new TypeInfo( binder, _altova_ni_xs, "gMonthDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonthDay.begin, _altova_mi_xs_altova_gMonthDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GMonthDayFormatter );
			types[74] = new TypeInfo( binder, _altova_ni_xs, "gYear", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYear.begin, _altova_mi_xs_altova_gYear.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GYearFormatter );
			types[75] = new TypeInfo( binder, _altova_ni_xs, "gYearMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYearMonth.begin, _altova_mi_xs_altova_gYearMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GYearMonthFormatter );
			types[76] = new TypeInfo( binder, _altova_ni_xs, "hexBinary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_hexBinary.begin, _altova_mi_xs_altova_hexBinary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.HexBinaryFormatter );
			types[77] = new TypeInfo( binder, _altova_ni_xs, "int", _altova_ti_xs_altova_long2, _altova_mi_xs_altova_int2.begin, _altova_mi_xs_altova_int2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "-2147483648", 0 ), 
					new FacetInfo (null, "maxInclusive", "2147483647", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[78] = new TypeInfo( binder, _altova_ni_xs, "integer", _altova_ti_xs_altova_decimal, _altova_mi_xs_altova_integer.begin, _altova_mi_xs_altova_integer.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[79] = new TypeInfo( binder, _altova_ni_xs, "language", _altova_ti_xs_altova_token, _altova_mi_xs_altova_language.begin, _altova_mi_xs_altova_language.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "pattern", "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[80] = new TypeInfo( binder, _altova_ni_xs, "long", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_long2.begin, _altova_mi_xs_altova_long2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "-9223372036854775808", 0 ), 
					new FacetInfo (null, "maxInclusive", "9223372036854775807", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[81] = new TypeInfo( binder, _altova_ni_xs, "negativeInteger", _altova_ti_xs_altova_nonPositiveInteger, _altova_mi_xs_altova_negativeInteger.begin, _altova_mi_xs_altova_negativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "maxInclusive", "-1", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[82] = new TypeInfo( binder, _altova_ni_xs, "nonNegativeInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonNegativeInteger.begin, _altova_mi_xs_altova_nonNegativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "0", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[83] = new TypeInfo( binder, _altova_ni_xs, "nonPositiveInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonPositiveInteger.begin, _altova_mi_xs_altova_nonPositiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "maxInclusive", "0", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[84] = new TypeInfo( binder, _altova_ni_xs, "normalizedString", _altova_ti_xs_altova_string2, _altova_mi_xs_altova_normalizedString.begin, _altova_mi_xs_altova_normalizedString.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "replace", 0 ),
				},
				WhitespaceType.Whitespace_Replace, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[85] = new TypeInfo( binder, _altova_ni_xs, "positiveInteger", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_positiveInteger.begin, _altova_mi_xs_altova_positiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "1", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[86] = new TypeInfo( binder, _altova_ni_xs, "short", _altova_ti_xs_altova_int2, _altova_mi_xs_altova_short2.begin, _altova_mi_xs_altova_short2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "-32768", 0 ), 
					new FacetInfo (null, "maxInclusive", "32767", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[87] = new TypeInfo( binder, _altova_ni_xs, "string", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_string2.begin, _altova_mi_xs_altova_string2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "preserve", 0 ),
				},
				WhitespaceType.Whitespace_Preserve, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[88] = new TypeInfo( binder, _altova_ni_xs, "time", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_time.begin, _altova_mi_xs_altova_time.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.TimeFormatter );
			types[89] = new TypeInfo( binder, _altova_ni_xs, "token", _altova_ti_xs_altova_normalizedString, _altova_mi_xs_altova_token.begin, _altova_mi_xs_altova_token.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[90] = new TypeInfo( binder, _altova_ni_xs, "unsignedByte", _altova_ti_xs_altova_unsignedShort, _altova_mi_xs_altova_unsignedByte.begin, _altova_mi_xs_altova_unsignedByte.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "0", 0 ), 
					new FacetInfo (null, "maxInclusive", "255", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[91] = new TypeInfo( binder, _altova_ni_xs, "unsignedInt", _altova_ti_xs_altova_unsignedLong, _altova_mi_xs_altova_unsignedInt.begin, _altova_mi_xs_altova_unsignedInt.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "0", 0 ), 
					new FacetInfo (null, "maxInclusive", "4294967295", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[92] = new TypeInfo( binder, _altova_ni_xs, "unsignedLong", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_unsignedLong.begin, _altova_mi_xs_altova_unsignedLong.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "0", 0 ), 
					new FacetInfo (null, "maxInclusive", "18446744073709551615", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[93] = new TypeInfo( binder, _altova_ni_xs, "unsignedShort", _altova_ti_xs_altova_unsignedInt, _altova_mi_xs_altova_unsignedShort.begin, _altova_mi_xs_altova_unsignedShort.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "minInclusive", "0", 0 ), 
					new FacetInfo (null, "maxInclusive", "65535", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.IntegerFormatter );
			types[94] = new TypeInfo( binder, _altova_ni_xs, "", 0, _altova_mi_xs_altova_doubleType.begin, _altova_mi_xs_altova_doubleType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.DoubleFormatter );
			types[95] = new TypeInfo( binder, _altova_ni_xs, "", 0, _altova_mi_xs_altova_dateTimeType.begin, _altova_mi_xs_altova_dateTimeType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.DateTimeFormatter );
			types[96] = new TypeInfo( binder, _altova_ni_xs, "", 0, _altova_mi_xs_altova_stringType.begin, _altova_mi_xs_altova_stringType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );

		}

		public TypeInfo[] createTypes(InfoBinderInterface binder) {

			TypeInfo types[] = new TypeInfo[97];

			initTypes0(binder, types);
			
			return types;

		}
	}

	// Array of all members
	public static final MemberInfo members[] = new MemberInfoCreator().createMembers(binder);

	private static class MemberInfoCreator
	{
		private void initMembers0(InfoBinderInterface binder, MemberInfo[] members) {
			members[0] = new MemberInfo (binder, "", "EnumeratedMetric", _altova_ti_altova_BaseMetric, _altova_ti_altova_EnumeratedMetricType, 0, 0, 1);
			members[1] = new MemberInfo (binder, "", "QuantitativeMetric", _altova_ti_altova_BaseMetric, _altova_ti_xs_altova_doubleType, 0, 0, 1);

			members[2] = new MemberInfo (binder, "", "latitude", _altova_ti_altova_Coordinate, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[3] = new MemberInfo (binder, "", "longitude", _altova_ti_altova_Coordinate, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[4] = new MemberInfo (binder, "", "depth", _altova_ti_altova_Coordinate, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[5] = new MemberInfo (binder, "", "orientation", _altova_ti_altova_Coordinate, _altova_ti_xs_altova_anyType, 0, 1, 1);

			members[6] = new MemberInfo (binder, "", "name", _altova_ti_altova_QoIMetric, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[7] = new MemberInfo (binder, "", "QoIEnumeratedMetric", _altova_ti_altova_QoIMetric, _altova_ti_altova_QoIEnumeratedMetricType, 0, 0, 1);
			members[8] = new MemberInfo (binder, "", "QoIQuantitativeMetric", _altova_ti_altova_QoIMetric, _altova_ti_altova_QoIQuantitativeMetricType, 0, 0, 1);

			members[9] = new MemberInfo (binder, "", "BaseData", _altova_ti_altova_MetaData, _altova_ti_altova_BaseDataType, 0, 0, 1);
			members[10] = new MemberInfo (binder, "", "BaseQoI", _altova_ti_altova_MetaData, _altova_ti_altova_BaseQoIType, 0, 0, 1);
			members[11] = new MemberInfo (binder, "", "BaseVoI", _altova_ti_altova_MetaData, _altova_ti_altova_BaseVoIType, 0, 0, 1);
			members[12] = new MemberInfo (binder, "", "Contact", _altova_ti_altova_MetaData, _altova_ti_altova_ContactType, 0, 0, 1);
			members[13] = new MemberInfo (binder, "", "Context", _altova_ti_altova_MetaData, _altova_ti_altova_ContextType, 0, 0, 1);
			members[14] = new MemberInfo (binder, "", "DataSource", _altova_ti_altova_MetaData, _altova_ti_altova_DataSourceType, 0, 0, 1);
			members[15] = new MemberInfo (binder, "", "Information", _altova_ti_altova_MetaData, _altova_ti_altova_InformationType, 0, 0, 1);
			members[16] = new MemberInfo (binder, "", "QoIBaseAttr", _altova_ti_altova_MetaData, _altova_ti_altova_QoIBaseAttrType, 0, 0, 1);
			members[17] = new MemberInfo (binder, "", "VoIBaseAttr", _altova_ti_altova_MetaData, _altova_ti_altova_VoIBaseAttrType, 0, 0, 1);

			members[18] = new MemberInfo (binder, "", "metric", _altova_ti_altova_BaseDataType, _altova_ti_altova_BaseMetric, 0, 1, 1);
			members[19] = new MemberInfo (binder, "", "location", _altova_ti_altova_BaseDataType, _altova_ti_altova_locationType, 0, 1, 1);
			members[20] = new MemberInfo (binder, "", "dateTime", _altova_ti_altova_BaseDataType, _altova_ti_xs_altova_dateTimeType, 0, 1, 1);

			members[21] = new MemberInfo (binder, "", "lon", _altova_ti_altova_locationType, _altova_ti_xs_altova_doubleType, 0, 1, 1);
			members[22] = new MemberInfo (binder, "", "lat", _altova_ti_altova_locationType, _altova_ti_xs_altova_doubleType, 0, 1, 1);

			members[23] = new MemberInfo (binder, "", "DataSource", _altova_ti_altova_BaseQoIType, _altova_ti_altova_DataSourceType, 0, 1, 1);
			members[24] = new MemberInfo (binder, "", "Context", _altova_ti_altova_BaseQoIType, _altova_ti_altova_ContextType, 0, 1, 1);
			members[25] = new MemberInfo (binder, "", "InformationQoI", _altova_ti_altova_BaseQoIType, _altova_ti_altova_InformationQoIType, 0, 0, -1);

			members[26] = new MemberInfo (binder, "", "id", _altova_ti_altova_DataSourceType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[27] = new MemberInfo (binder, "", "publishDate", _altova_ti_altova_DataSourceType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[28] = new MemberInfo (binder, "", "role", _altova_ti_altova_DataSourceType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[29] = new MemberInfo (binder, "", "isOwnedBy", _altova_ti_altova_DataSourceType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[30] = new MemberInfo (binder, "", "publisher", _altova_ti_altova_DataSourceType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[31] = new MemberInfo (binder, "", "Sensor", _altova_ti_altova_DataSourceType, _altova_ti_altova_SensorType, 0, 0, 1);
			members[32] = new MemberInfo (binder, "", "Human", _altova_ti_altova_DataSourceType, _altova_ti_altova_HumanType, 0, 0, 1);
			members[33] = new MemberInfo (binder, "", "DataSourceQoI", _altova_ti_altova_DataSourceType, _altova_ti_altova_DataSourceQoIType, 0, 1, 1);

			members[34] = new MemberInfo (binder, "", "AppDomainCntx", _altova_ti_altova_ContextType, _altova_ti_altova_AppDomainCntxType2, 0, 1, 1);
			members[35] = new MemberInfo (binder, "", "QoISpatialCntxAttr", _altova_ti_altova_ContextType, _altova_ti_altova_QoISpatialCntxAttrType, 0, 0, 1);
			members[36] = new MemberInfo (binder, "", "QoITemperalCntxAttr", _altova_ti_altova_ContextType, _altova_ti_altova_QoITemperalCntxAttrType, 0, 0, 1);

			members[37] = new MemberInfo (binder, "", "id", _altova_ti_altova_InformationQoIType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[38] = new MemberInfo (binder, "", "QoIBaseAttr", _altova_ti_altova_InformationQoIType, _altova_ti_altova_QoIBaseAttrType, 0, 0, -1);

			members[39] = new MemberInfo (binder, "", "name", _altova_ti_altova_QoIBaseAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[40] = new MemberInfo (binder, "", "id", _altova_ti_altova_QoIBaseAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[41] = new MemberInfo (binder, "", "QoIIntegrityAttr", _altova_ti_altova_QoIBaseAttrType, _altova_ti_altova_QoIIntegrityAttrType, 0, 0, 1);
			members[42] = new MemberInfo (binder, "", "QoIAccuracyAttr", _altova_ti_altova_QoIBaseAttrType, _altova_ti_altova_QoIAccuracyAttrType, 0, 0, 1);
			members[43] = new MemberInfo (binder, "", "QoITimelinessAttr", _altova_ti_altova_QoIBaseAttrType, _altova_ti_altova_QoITimelinessAttrType, 0, 0, 1);
			members[44] = new MemberInfo (binder, "", "QoIFormatAttr", _altova_ti_altova_QoIBaseAttrType, _altova_ti_altova_QoIFormatAttrType, 0, 0, 1);

			members[45] = new MemberInfo (binder, "", "VoIBaseAttr", _altova_ti_altova_BaseVoIType, _altova_ti_altova_VoIBaseAttrType, 0, 0, -1);
			members[46] = new MemberInfo (binder, "", "Context", _altova_ti_altova_BaseVoIType, _altova_ti_altova_ContextType2, 0, 1, 1);

			members[47] = new MemberInfo (binder, "", "name", _altova_ti_altova_VoIBaseAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[48] = new MemberInfo (binder, "", "id", _altova_ti_altova_VoIBaseAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[49] = new MemberInfo (binder, "", "VoIUsefulnessAttr", _altova_ti_altova_VoIBaseAttrType, _altova_ti_altova_VoIUsefulnessAttrType, 0, 0, 1);
			members[50] = new MemberInfo (binder, "", "VoITrustAttr", _altova_ti_altova_VoIBaseAttrType, _altova_ti_altova_VoITrustAttrType, 0, 0, 1);
			members[51] = new MemberInfo (binder, "", "VoIConvenienceAttr", _altova_ti_altova_VoIBaseAttrType, _altova_ti_altova_VoIConvenienceAttrType, 0, 0, 1);

			members[52] = new MemberInfo (binder, "", "AppDomainCntx", _altova_ti_altova_ContextType2, _altova_ti_altova_AppDomainCntxType, 0, 1, 1);

			members[53] = new MemberInfo (binder, "", "description", _altova_ti_altova_AppDomainCntxType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[54] = new MemberInfo (binder, "", "name", _altova_ti_altova_AppDomainCntxType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[55] = new MemberInfo (binder, "", "standardName", _altova_ti_altova_AppDomainCntxType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[56] = new MemberInfo (binder, "", "standardDescription", _altova_ti_altova_AppDomainCntxType, _altova_ti_xs_altova_stringType, 0, 1, 1);

			members[57] = new MemberInfo (binder, "", "name", _altova_ti_altova_ContactType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[58] = new MemberInfo (binder, "", "organization", _altova_ti_altova_ContactType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[59] = new MemberInfo (binder, "", "position", _altova_ti_altova_ContactType, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[60] = new MemberInfo (binder, "", "phone", _altova_ti_altova_ContactType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[61] = new MemberInfo (binder, "", "email", _altova_ti_altova_ContactType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[62] = new MemberInfo (binder, "", "eid", _altova_ti_altova_ContactType, _altova_ti_xs_altova_anyType, 0, 1, 1);

			members[63] = new MemberInfo (binder, "", "id", _altova_ti_altova_InformationType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[64] = new MemberInfo (binder, "", "type", _altova_ti_altova_InformationType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[65] = new MemberInfo (binder, "", "BaseQoI", _altova_ti_altova_InformationType, _altova_ti_altova_BaseQoIType, 0, 1, 1);
			members[66] = new MemberInfo (binder, "", "BaseVoI", _altova_ti_altova_InformationType, _altova_ti_altova_BaseVoIType, 0, 1, 1);
			members[67] = new MemberInfo (binder, "", "BaseData", _altova_ti_altova_InformationType, _altova_ti_altova_BaseDataType, 0, 1, 1);

			members[68] = new MemberInfo (binder, "", "selectedValue", _altova_ti_altova_EnumeratedMetricType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[69] = new MemberInfo (binder, "", "permissibleValues", _altova_ti_altova_EnumeratedMetricType, _altova_ti_xs_altova_anyType, 0, 1, -1);

			members[70] = new MemberInfo (binder, "", "selectedValue", _altova_ti_altova_QoIEnumeratedMetricType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[71] = new MemberInfo (binder, "", "permissibleValues", _altova_ti_altova_QoIEnumeratedMetricType, _altova_ti_xs_altova_anyType, 0, 1, -1);

			members[72] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_QoIQuantitativeMetricType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[73] = new MemberInfo (binder, "", "errorRange", _altova_ti_altova_QoIQuantitativeMetricType, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[74] = new MemberInfo (binder, "", "biasError", _altova_ti_altova_QoIQuantitativeMetricType, _altova_ti_xs_altova_anyType, 0, 1, 1);

			members[75] = new MemberInfo (binder, "", "Contact", _altova_ti_altova_SensorType, _altova_ti_altova_ContactType, 0, 1, 1);
			members[76] = new MemberInfo (binder, "", "identification", _altova_ti_altova_SensorType, _altova_ti_altova_identificationType, 0, 1, 1);
			members[77] = new MemberInfo (binder, "", "classification", _altova_ti_altova_SensorType, _altova_ti_altova_classificationType, 0, 1, 1);
			members[78] = new MemberInfo (binder, "", "validTime", _altova_ti_altova_SensorType, _altova_ti_altova_validTimeType, 0, 1, 1);
			members[79] = new MemberInfo (binder, "", "characteristics", _altova_ti_altova_SensorType, _altova_ti_altova_characteristicsType, 0, 1, 1);
			members[80] = new MemberInfo (binder, "", "capabilities", _altova_ti_altova_SensorType, _altova_ti_altova_capabilitiesType, 0, 1, 1);
			members[81] = new MemberInfo (binder, "", "Components", _altova_ti_altova_SensorType, _altova_ti_altova_ComponentsType, 0, 1, 1);

			members[82] = new MemberInfo (binder, "", "uid", _altova_ti_altova_identificationType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[83] = new MemberInfo (binder, "", "shortName", _altova_ti_altova_identificationType, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[84] = new MemberInfo (binder, "", "longName", _altova_ti_altova_identificationType, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[85] = new MemberInfo (binder, "", "manufacturer", _altova_ti_altova_identificationType, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[86] = new MemberInfo (binder, "", "modelNumber", _altova_ti_altova_identificationType, _altova_ti_xs_altova_anyType, 0, 1, 1);
			members[87] = new MemberInfo (binder, "", "deviceId", _altova_ti_altova_identificationType, _altova_ti_xs_altova_anyType, 0, 1, 1);

			members[88] = new MemberInfo (binder, "", "sensorType", _altova_ti_altova_classificationType, _altova_ti_xs_altova_anyType, 0, 1, 1);

			members[89] = new MemberInfo (binder, "", "start", _altova_ti_altova_validTimeType, _altova_ti_xs_altova_date, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[90] = new MemberInfo (binder, "", "end", _altova_ti_altova_validTimeType, _altova_ti_xs_altova_date, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[91] = new MemberInfo (binder, "", "weight", _altova_ti_altova_characteristicsType, _altova_ti_altova_weightType, 0, 1, 1);
			members[92] = new MemberInfo (binder, "", "height", _altova_ti_altova_characteristicsType, _altova_ti_altova_heightType, 0, 1, 1);
			members[93] = new MemberInfo (binder, "", "width", _altova_ti_altova_characteristicsType, _altova_ti_altova_widthType, 0, 1, 1);
			members[94] = new MemberInfo (binder, "", "material", _altova_ti_altova_characteristicsType, _altova_ti_altova_materialType, 0, 1, 1);
			members[95] = new MemberInfo (binder, "", "length", _altova_ti_altova_characteristicsType, _altova_ti_altova_lengthType, 0, 1, 1);

			members[96] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_weightType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[97] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_heightType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[98] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_widthType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[99] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_materialType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[100] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_lengthType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[101] = new MemberInfo (binder, "", "sampleRate", _altova_ti_altova_capabilitiesType, _altova_ti_altova_sampleRateType, 0, 1, 1);
			members[102] = new MemberInfo (binder, "", "batteryLife", _altova_ti_altova_capabilitiesType, _altova_ti_altova_batteryLifeType, 0, 1, 1);
			members[103] = new MemberInfo (binder, "", "powerCurrent", _altova_ti_altova_capabilitiesType, _altova_ti_altova_powerCurrentType, 0, 1, 1);

			members[104] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_sampleRateType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[105] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_batteryLifeType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[106] = new MemberInfo (binder, "", "uofm", _altova_ti_altova_powerCurrentType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[107] = new MemberInfo (binder, "", "component", _altova_ti_altova_ComponentsType, _altova_ti_altova_componentType, 0, 1, -1);

			members[108] = new MemberInfo (binder, "", "Contact", _altova_ti_altova_HumanType, _altova_ti_altova_ContactType, 0, 1, 1);

			members[109] = new MemberInfo (binder, "", "QoIBaseAttr", _altova_ti_altova_DataSourceQoIType, _altova_ti_altova_QoIBaseAttrType, 0, 0, -1);

			members[110] = new MemberInfo (binder, "", "description", _altova_ti_altova_AppDomainCntxType2, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[111] = new MemberInfo (binder, "", "name", _altova_ti_altova_AppDomainCntxType2, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[112] = new MemberInfo (binder, "", "standardName", _altova_ti_altova_AppDomainCntxType2, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[113] = new MemberInfo (binder, "", "standardDescription", _altova_ti_altova_AppDomainCntxType2, _altova_ti_xs_altova_stringType, 0, 1, 1);

			members[114] = new MemberInfo (binder, "", "name", _altova_ti_altova_QoISpatialCntxAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[115] = new MemberInfo (binder, "", "lowerBound", _altova_ti_altova_QoISpatialCntxAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[116] = new MemberInfo (binder, "", "upperBound", _altova_ti_altova_QoISpatialCntxAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[117] = new MemberInfo (binder, "", "name", _altova_ti_altova_QoITemperalCntxAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[118] = new MemberInfo (binder, "", "startTime", _altova_ti_altova_QoITemperalCntxAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[119] = new MemberInfo (binder, "", "endTime", _altova_ti_altova_QoITemperalCntxAttrType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[120] = new MemberInfo (binder, "", "lowerBound", _altova_ti_altova_QoITemperalCntxAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[121] = new MemberInfo (binder, "", "upperBound", _altova_ti_altova_QoITemperalCntxAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[122] = new MemberInfo (binder, "", "eventType", _altova_ti_altova_QoITemperalCntxAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[123] = new MemberInfo (binder, "", "sourceIntegrity", _altova_ti_altova_QoIIntegrityAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[124] = new MemberInfo (binder, "", "channelIntegrity", _altova_ti_altova_QoIIntegrityAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[125] = new MemberInfo (binder, "", "auditability", _altova_ti_altova_QoIIntegrityAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[126] = new MemberInfo (binder, "", "attestability", _altova_ti_altova_QoIIntegrityAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[127] = new MemberInfo (binder, "", "confidentiality", _altova_ti_altova_QoIIntegrityAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[128] = new MemberInfo (binder, "", "volatility", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[129] = new MemberInfo (binder, "", "detailLevel", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[130] = new MemberInfo (binder, "", "volume", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[131] = new MemberInfo (binder, "", "consistency", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[132] = new MemberInfo (binder, "", "resolution", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[133] = new MemberInfo (binder, "", "bias", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[134] = new MemberInfo (binder, "", "errorLevel", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[135] = new MemberInfo (binder, "", "errorRate", _altova_ti_altova_QoIAccuracyAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[136] = new MemberInfo (binder, "", "latencySource", _altova_ti_altova_QoITimelinessAttrType, _altova_ti_xs_altova_doubleType, 0, 1, 1);
			members[137] = new MemberInfo (binder, "", "detailLevel", _altova_ti_altova_QoITimelinessAttrType, _altova_ti_xs_altova_doubleType, 0, 1, 1);
			members[138] = new MemberInfo (binder, "", "validityExpiration", _altova_ti_altova_QoITimelinessAttrType, _altova_ti_xs_altova_doubleType, 0, 1, 1);
			members[139] = new MemberInfo (binder, "", "timelinessLevel", _altova_ti_altova_QoITimelinessAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[140] = new MemberInfo (binder, "", "encoding", _altova_ti_altova_QoIFormatAttrType, _altova_ti_xs_altova_doubleType, 0, 1, 1);
			members[141] = new MemberInfo (binder, "", "conciseness", _altova_ti_altova_QoIFormatAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[142] = new MemberInfo (binder, "", "novelty", _altova_ti_altova_VoIUsefulnessAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[143] = new MemberInfo (binder, "", "revelance", _altova_ti_altova_VoIUsefulnessAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[144] = new MemberInfo (binder, "", "timeliness", _altova_ti_altova_VoIUsefulnessAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[145] = new MemberInfo (binder, "", "completeness", _altova_ti_altova_VoIUsefulnessAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[146] = new MemberInfo (binder, "", "sourceReputation", _altova_ti_altova_VoITrustAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[147] = new MemberInfo (binder, "", "channelReputation", _altova_ti_altova_VoITrustAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[148] = new MemberInfo (binder, "", "sourceObjectivity", _altova_ti_altova_VoITrustAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[149] = new MemberInfo (binder, "", "easeOfUse", _altova_ti_altova_VoIConvenienceAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[150] = new MemberInfo (binder, "", "formatCompatibility", _altova_ti_altova_VoIConvenienceAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);
			members[151] = new MemberInfo (binder, "", "composability", _altova_ti_altova_VoIConvenienceAttrType, _altova_ti_altova_QoIMetric, 0, 1, 1);

			members[152] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_anyType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

			members[153] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_doubleType, _altova_ti_xs_altova_double2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[154] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_dateTimeType, _altova_ti_xs_altova_dateTime, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[155] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_stringType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

		}

		public MemberInfo[] createMembers(InfoBinderInterface binder) {

			MemberInfo members[] = new MemberInfo[156];

			initMembers0(binder, members);
			
			return members;

		}
	}
}
