////////////////////////////////////////////////////////////////////////
//
// ContextType2.java
//
// This file was generated by XMLSpy 2014 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

package com.MetaData;

public class ContextType2 extends com.altova.xml.TypeBase
{
	public static com.altova.xml.meta.ComplexType getStaticInfo() { return new com.altova.xml.meta.ComplexType(com.MetaData.MetaData_TypeInfo.binder.getTypes()[com.MetaData.MetaData_TypeInfo._altova_ti_altova_ContextType2]); }
	
	public ContextType2(org.w3c.dom.Node init)
	{
		super(init);
		instantiateMembers();
	}

	private void instantiateMembers()
	{

		AppDomainCntx= new MemberElement_AppDomainCntx (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_ContextType2._AppDomainCntx]);
	}
	// Attributes


	// Elements
	
	public MemberElement_AppDomainCntx AppDomainCntx;

		public static class MemberElement_AppDomainCntx
		{
			public static class MemberElement_AppDomainCntx_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_AppDomainCntx member;
				public MemberElement_AppDomainCntx_Iterator(MemberElement_AppDomainCntx member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					AppDomainCntxType nx = new AppDomainCntxType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_AppDomainCntx (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public AppDomainCntxType at(int index) {return new AppDomainCntxType(owner.getElementAt(info, index));}
			public AppDomainCntxType first() {return new AppDomainCntxType(owner.getElementFirst(info));}
			public AppDomainCntxType last(){return new AppDomainCntxType(owner.getElementLast(info));}
			public AppDomainCntxType append(){return new AppDomainCntxType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_AppDomainCntx_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
}
