////////////////////////////////////////////////////////////////////////
//
// QoIMetric.java
//
// This file was generated by XMLSpy 2014 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

package com.MetaData;

public class QoIMetric extends com.altova.xml.TypeBase
{
	public static com.altova.xml.meta.ComplexType getStaticInfo() { return new com.altova.xml.meta.ComplexType(com.MetaData.MetaData_TypeInfo.binder.getTypes()[com.MetaData.MetaData_TypeInfo._altova_ti_altova_QoIMetric]); }
	
	public QoIMetric(org.w3c.dom.Node init)
	{
		super(init);
		instantiateMembers();
	}

	private void instantiateMembers()
	{
		name = new MemberAttribute_name (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_QoIMetric._name]);

		QoIEnumeratedMetric= new MemberElement_QoIEnumeratedMetric (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_QoIMetric._QoIEnumeratedMetric]);
		QoIQuantitativeMetric= new MemberElement_QoIQuantitativeMetric (this, com.MetaData.MetaData_TypeInfo.binder.getMembers()[com.MetaData.MetaData_TypeInfo._altova_mi_altova_QoIMetric._QoIQuantitativeMetric]);
	}
	// Attributes
	public MemberAttribute_name name;
		public static class MemberAttribute_name
		{
			private com.altova.xml.TypeBase owner;
			private com.altova.typeinfo.MemberInfo info; 
			public MemberAttribute_name (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) {this.owner = owner; this.info = info;}
			public String getValue() {
				return (String)com.altova.xml.XmlTreeOperations.castToString(com.altova.xml.XmlTreeOperations.findAttribute(owner.getNode(), info), info);
			}
			public void setValue(String value) {
				com.altova.xml.XmlTreeOperations.setValue(owner.getNode(), info, value);		
			}
			public boolean exists() {return owner.getAttribute(info) != null;}
			public void remove() {owner.removeAttribute(info);} 
			public com.altova.xml.meta.Attribute getInfo() {return new com.altova.xml.meta.Attribute(info);}

		}


	// Elements
	
	public MemberElement_QoIEnumeratedMetric QoIEnumeratedMetric;

		public static class MemberElement_QoIEnumeratedMetric
		{
			public static class MemberElement_QoIEnumeratedMetric_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_QoIEnumeratedMetric member;
				public MemberElement_QoIEnumeratedMetric_Iterator(MemberElement_QoIEnumeratedMetric member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					QoIEnumeratedMetricType nx = new QoIEnumeratedMetricType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_QoIEnumeratedMetric (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public QoIEnumeratedMetricType at(int index) {return new QoIEnumeratedMetricType(owner.getElementAt(info, index));}
			public QoIEnumeratedMetricType first() {return new QoIEnumeratedMetricType(owner.getElementFirst(info));}
			public QoIEnumeratedMetricType last(){return new QoIEnumeratedMetricType(owner.getElementLast(info));}
			public QoIEnumeratedMetricType append(){return new QoIEnumeratedMetricType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_QoIEnumeratedMetric_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
	
	public MemberElement_QoIQuantitativeMetric QoIQuantitativeMetric;

		public static class MemberElement_QoIQuantitativeMetric
		{
			public static class MemberElement_QoIQuantitativeMetric_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_QoIQuantitativeMetric member;
				public MemberElement_QoIQuantitativeMetric_Iterator(MemberElement_QoIQuantitativeMetric member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					QoIQuantitativeMetricType nx = new QoIQuantitativeMetricType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_QoIQuantitativeMetric (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public QoIQuantitativeMetricType at(int index) {return new QoIQuantitativeMetricType(owner.getElementAt(info, index));}
			public QoIQuantitativeMetricType first() {return new QoIQuantitativeMetricType(owner.getElementFirst(info));}
			public QoIQuantitativeMetricType last(){return new QoIQuantitativeMetricType(owner.getElementLast(info));}
			public QoIQuantitativeMetricType append(){return new QoIQuantitativeMetricType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_QoIQuantitativeMetric_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}

		public void setXsiType() {com.altova.xml.XmlTreeOperations.setAttribute(getNode(), "http://www.w3.org/2001/XMLSchema-instance", "xsi:type", "", "QoIMetric");}
}
